base_url = "https://novos.srclo.net"

# directory mapping
posts_dir   = "./posts"
pages_dir   = "./pages"
static_dir  = "./static"
output_dir  = "./.build"
base = ""

# template paths
template_path      = "./index.html"
includes_dir       = "./includes"
view_template_path = "./includes/view_template.html"