base_url = "https://novos.sh"
# base_url = "http://localhost:8080"
base = ""

posts_dir    = "./posts"
pages_dir    = "./pages"
static_dir   = "./static"
output_dir   = "./.build"
posts_outdir = "docs/"


[site]
title = "novos"
description = "A fast, minimal static site generater."
author = "contributors"
generate_rss = true
generate_search = true

[build]
clean_output = true
minify_html = true
# syntax_theme = "InspiredGitHub"
syntax_theme_path = "./static/themes/solarnight.tmTheme"
use_syntect = true
sass_style = "compressed"
convert_to_webp = true