[theme]
name = "nordish"
author = "novos"
version = "0.1.0"
license = "MIT OR Apache-2.0"
description = "A clean, frosty, Nord inspired theme."

[extra]
show_avatar = true
github_url = "https://github.com/novos-org"


[build]
syntax_theme_path = "static/themes/nordish.tmTheme"

[paths]
sass_main = "sass/nordish.scss"
templates_dir = "templates"
static_dir = "static"